### ISSUE TITLE
Application hooks

### ISSUE THREAD

**Issue by vadim-zabolotniy** [JovianX/Service-Hub#117]
Add application hooks in template. This should be `hooks` root attribute in template with next events:

- **pre_install** - Hooks which is executing before application launch.
- **post_install** - Hooks which is executing after application launch.
- **pre_upgrade** - Hooks which is executing before application template upgrade launch.
- **post_upgrade** - Hooks which is executing after application template upgrade launch.
- **pre_delete** - Hooks which is executing before application deletion.
- **post_delete** - Hooks which is executing after application deletion.

Common schema:
```yaml
hooks:
  pre_install:
    ...
  post_install:
    ...

  pre_update:
    ...
  post_update:
    ...

  pre_delete:
    ...
  post_delete:
    ...
```

Each of event can contain list of hook descriptions with next attributes:
- **name** - Required. Name of hook. Must be unique across all event hooks.
- **kube_context** - Optional. Name of context to use during Kubernetes Job creation. If omitted application Kubernetes context will be use.
- **namespace** - Optional. Name of namespace where Kubernetes Job will be created. If omitted application namespace will be use.
- **service_account_name** - Optional. Kubernetes service account name to use during Kubernetes Job creation. If omitted will be set to `default`. 
- **on_failure** - Optional. Behavior on hook failure. Can have two options `continue` and `stop`. If `continue` hook crashed or reached timeout further other hooks and application execution will continue. If `stop` hook crash or reaching timeout will cause application action(install, upgrade, delete) to fail.
- **timeout** - Optional. How long hook can execute until will be considered as overdue.
- **type** - Required. Type of hook. For now available only `kubernetes_job`. 
- **image** - Required if `type` is `kubernetes_job`. Kubernetes pod image to use.
- **command** - Required if `type` is `kubernetes_job`. Kubernetes pod command to execute.
- **args** - Required if `type` is `kubernetes_job`. Kubernetes pod command arguments.
- **env** - Optional. Used when `type` is `kubernetes_job`. Environment variable to set in Kubernetes pod. Must be list of mappings with `name` and `value` parameters.

Full example:
```yaml
hooks:
  pre_install:
    - name: pre-install-hook
      # kube_context: jovianx-admin-jovianx-system-gke_jovianx-dev-workload_us-central1-a_jovianx-dev
      namespace: jovianx-system
      service_account_name: jovianx-admin
      on_failure: stop # continue | stop
      timeout: 120
      type: kubernetes_job
      image: 'alpine'
      command: ['/bin/sh', '-c']
      args:
        - env; sleep 1;
      env:
        - name: JX_ENV_KEY
          value: "Hello World"
        - name: CUSTOMER_ACCOUNT_NAME
          value: "{{ account://end_company }}"

  post_install:
    - name: post-install-user-add
      type: kubernetes_job
      image: 'appropriate/curl'
      command: ['/bin/sh', '-c']
      args:
        - curl {{ application://endpoints/keepalive_agent_ep/ip }}/api/add_user?user={{ account://admin_email }}&password={{ account://admin_password }};

  pre_update:
    - name: pre-update-web-hook
      timeout: 10
      on_failure: stop
      type: kubernetes_job
      image: 'appropriate/curl'
      command: ['/bin/sh', '-c']
      args:
        - curl https://www.google.com/search?q=pre_update_hook

  post_update:
    - name: post-update-web-hook
      timeout: 10
      type: kubernetes_job
      image: 'appropriate/curl'
      command: ['/bin/sh', '-c']
      args:
        - curl https://www.google.com/search?q=post_update_hook

  pre_delete:
    - name: pre-delete-web-hook
      timeout: 10
      type: kubernetes_job
      image: 'appropriate/curl'
      command: ['/bin/sh', '-c']
      args:
        - curl https://www.google.com/search?q=pre_delete_hook

```
