### ISSUE TITLE
Update welcome and add cluster modals

### ISSUE THREAD

**Issue by rtpro** [JovianX/Service-Hub#196]
- [x] In the welcome modal, under welcome the text, add checkboxes as the following:

```
  - [X] Create an account 
  - [ ] Connect to a Kubernetes cluster
```

- [x] In the Copy/Paste command update text to:
  - [x] Above the field `Copy the command below to add a Kubernetes cluster via configured kubectl:`
  - [x] Below the field `Paste and run command in a terminal where Kubectl is configured.`

- [x] Under `Settings > Clusters > Add Cluster screen`, Add the following default Kubeconfig field,:

```YAML
---
kind: Config
apiVersion: v1
current-context: example-context
clusters:
- cluster:
    certificate-authority-data: dG9rZW4=
    server: https://42.42.42.42
  name: example-cluster
contexts:
- context:
    cluster: example-cluster
    namespace: example-namespace
    user: example-user
  name: example-context
users:
- user:
    token: example-user-token
  name: example-user
preferences: {}
```

- [ ] Welcome screen should be shown only after the API returns a response that no clusters are configured
