### ISSUE TITLE
Template: it should be possible to enable/disable components via inputs

### ISSUE THREAD

**Issue by rtpro** [JovianX/Service-Hub#210]
In the Application Template: it should be possible to enable/disable components via inputs, ie It should be okay to set this template:

```
name: dev_stack
components:
  - name: redis
    type: helm_chart
    chart: bitnami/redis
    enabled: {{inputs.enable_redis}}
    version: 17.3.14
  - name: postgres
    type: helm_chart
    chart: bitnami/postgresql
    version: 12.1.3
inputs:
  - name: enable_redis
    type: switch
    label: Enable Redis
    default: true
  - name: enable_postgres
    type: switch
    label: Enable PstgresSQL
    default: true
```

This produces an error 
```
Template is invalid. components -> 0 -> enabled value could not be parsed to a boolean (type=type_error.bool)
```

![Image](https://user-images.githubusercontent.com/2787296/206903782-57abebbe-728c-4530-9530-3b2050f313f8.png)
