### ISSUE TITLE
Template variable error logging

### ISSUE THREAD

**Issue by vadim-zabolotniy** [JovianX/Service-Hub#270]
Template example:
```
name: redis
inputs:
  - name: password
    type: password
    label: Password
    default: ''
    description: Choose a password or Redis
components:
  - name: redis
    type: helm_chart
    chart: bitnami/redis
    version: 17.0.6
    values:
      - auth:
          password: '{{ inputs.password }}'
      - master:
          service:
            type: LoadBalancer
outputs:
  notes: '{{components.redis.manifest.Service.redis-master.status.load_balancer.ingress[0].ip}}'
```

IP address of Redis load balancer(`{{components.redis.manifest.Service.redis-master.status.load_balancer.ingress[0].ip}}`) is not printing.

Need to find out why and print error why template variable is not valid.
