### ISSUE TITLE
Add support for HTTP component

### ISSUE THREAD

**Issue by rtpro** [JovianX/Service-Hub#280]
Proposed template:
```
components:
  - name: name
    type: http
    deploy:
      url: https://httpbin.org/get
      method: get
      parameters:
      - my_text: '{{inputs.my_text}}'
    delete:
      url: https://httpbin.org/delete
      method: delete
      parameters: 
      - my_text: '{{inputs.my_text}}'
    status:
      url: https://httpbin.org/status
      method: get
      parameters: 
      - my_text: '{{inputs.my_text}}'    
name: http_service
inputs:
  - name: my_text
    type: text
    label: Some text to send
    default: hello
```
