### ISSUE TITLE
Adding template to README

### ISSUE THREAD

**Issue by rtpro** [JovianX/Service-Hub#35]
```

name: myapp     # required

charts:
  - name: test-jovianx20-application-nginx-ingress
    chart: nginx-stable/nginx-ingress
    version: 0.14.0
    values:
      # Inline values, passed via a temporary values file and --values, so that it doesn't suffer from type issues like --set
      - address: https://vault.example.com
        someparam:
            nested:
                morenest: cool
        db:
          username: {{ inputs.username }}

      - controller:
          ingressClass: {{ inputs.ingress_class_name }}
  - name: vadim-jovianx20-redis
    chart: bitnami/redis
    version: 17.0.6
    values:
      - url: https://vault.example.com
        someparam:
            nested:
                morenest: cool
        db:
          username: {{ inputs.username }}



inputs:                 # optional
  - name: username      # required
    type: string        # required, Options: string, select, checkbox
    lable: 'User Name'  # optional
    defualt: 'user'     # optional
  - name: ingress_class_name
    type: string
    lable: 'Nginx ingress class name'
    defualt: nginx
```
