### ISSUE TITLE
UI to Upload Kubeconfig

### ISSUE THREAD

**Issue by rtpro** [JovianX/Service-Hub#63]
On the cluster page, Add an "Add" button:

The button opens a modal that shows 2 options for adding a Cluster 
1. Copy/Paste terminal style command (The user would copy it and run it in his local terminal)
![image](https://user-images.githubusercontent.com/2787296/190111298-d45b6212-a779-4f9a-a3f0-b04fa565223a.png)

2. Paste the Kubernetes configuration file into a YAML editor (https://wangchujiang.com/react-monacoeditor/)

---

- PUT Endpoint to add a Kubernetes configuration: `/api/v1/organization/kubernetes-configuration`

---

YAML Example of Kubernetes configuration
```YAML
clusters:
  - name: some-cluster1
    region: unrecognized
    cloud_provider: unrecognized
  - name: some-cluster
    region: unrecognized
    cloud_provider: unrecognized
  - name: gke_jovianx-dev-workload_us-central1-a_jovianx-dev
    region: us-central1-a
    cloud_provider: gcp
contexts:
  - name: some-context1
    cluster: some-cluster1
    user: some-user
  - name: some-context
    cluster: some-cluster
    user: some-user
  - name: jovianx-admin-jovianx-system-gke_jovianx-dev-workload_us-central1-a_jovianx-dev
    cluster: gke_jovianx-dev-workload_us-central1-a_jovianx-dev
    user: jovianx-admin-jovianx-system-gke_jovianx-dev-workload_us-central1-a_jovianx-dev
users:
  - name: some-user
  - name: jovianx-admin-jovianx-system-gke_jovianx-dev-workload_us-central1-a_jovianx-dev
current_context: some-context

```
